remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"
title: Web Dev Projects
description: Web dev projects by Steven Coy.

plugins:
  - jekyll-include-cache
  - jekyll-target-blank
