remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"
title: Steven Coy Web Developer Projects
description: Steven Coy Web Developer Projects

plugins:
  - jekyll-include-cache
